# spring configuration
spring:
   application:
      name: plendar

   # devtools - live reload
   devtools:
      livereload:
         enabled: true
          
   mvc:
      # Path pattern used for static resources
      static-path-pattern: /asstes/**
      throw-exception-if-no-handler-found: true
      

   web:
      resources:
         # Locations of static resources
         static-locations: classpath:/static/

   thymeleaf:
      prefix: classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix: .html
      cache: false
   
      
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.10.39:3306/webdb
      username: webdb
      password: ENC(VJoDO7UAQnwTWVxdJ0B0K5A75a9gglBVGaYrQ3P+nNWd/EIifYTJ85tcxDSQYnm2)
      hikari:
           minimum-idle: 10
           maximum-pool-size: 20
jasypt:
   encryptor:
      bean: jasyptStringEncryptor
      
mybatis:
    config-location: classpath:mybatis/configuration.xml

server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         
# logging configuration
logging:
   level:
      root: INFO