# spring configuration
spring:
   application:
      name: plendar

   mvc:
      # Path pattern used for static resources
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true

   web:
      resources:
         static-locations: classpath:/assets/, file:/plendar-uploads/

   thymeleaf:
      prefix: classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix: .html
      cache: false
   
   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB
         
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://34.64.81.221:3306/plendar?characterEncoding=utf8
      username: ENC(bm+3OxWFqFign+Nd+Dp3Op30vcOlTPTlXiKAuGKT1cAMhup5fuFKRLxfySTjfoH3)
      password: ENC(9UKbp63zb6Dia33ahXsonli6aEffomUYpgM26cVHbG+5/D/Xzq2zwhoJABERUEjmIlAxy/Aw6C+SvH3aIIq61w==)
      hikari:
           minimum-idle: 10
           maximum-pool-size: 20
   
jasypt:
   encryptor:
      bean: jasyptStringEncryptor

mybatis:
    config-location: classpath:mybatis/configuration.xml
    
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
   file:
      name: logs/${spring.application.name}.log
      max-history: 30
   level:
      root: INFO
      com:
         jeonwoojo:
            plendar:
               exception: ERROR

---
# development profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: development

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true

---
# production profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: production

server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
          